# Generated by Django 4.0.2 on 2022-07-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_usertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='heigth',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='weigth',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Pattient',
        ),
    ]
