# Generated by Django 4.0.2 on 2022-07-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_user_birthdate_user_heigth_user_weigth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.CharField(max_length=15),
        ),
    ]
